# Site
# 博客的名称
title: Hollysys
# 根据主题的不同，有的会显示有的不会显示。
subtitle: Stay Hungry, Stay Foolish
# 主要用于SEO，告诉搜索引擎一个关于站点的简单描述，通常建议在其中包含网站的关键词
description:
keywords:
author: Hollysyser
language: zh-Hans
timezone: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# 一般填写自己的站点链接
url: http://unclepis.coding.me/hollysys/
root: /hollysys
# 生成的链接的格式
permalink: :year/:month/:day/:title/
#生成链接中各部分的默认值
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - CNAME

# Writing
new_post_name: :title.md # File name of new posts 新的博文的文件名
default_layout: post #默认布局
titlecase: false # Transform title into titlecase 
external_link: true # Open external links in new tab
filename_case: 0 #把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false #是否显示草稿
post_asset_folder: true  #创建同名的folder引入图片到md文件
relative_link: false
future: true
highlight: #代码块的设置，Hexo自带的代码高亮插件
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

Extensions:
# 搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: next #主题拓展，可以在主题商店选择其他主题，这里使用next 
# theme: yilia

# Schemes  # NexT 主题提供三种布局
#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  #repository: https://git.coding.net/unclepis/hollysys.git
  #branch: master
  repo:
      gitee: git@gitee.com:hanfanren/openSourse.git,master
      coding: https://git.coding.net/unclepis/hollysys.git,master

reward_comment: 初到贵宝地，有钱的给个钱场,没钱的挤一挤给个钱场...
wechatpay: https://raw.githubusercontent.com/Bored-AnnoYing/pic/master/pay/WeChatpay.png
alipay: https://github.com/Bored-AnnoYing/pic/blob/master/pay/Alipay.png?raw=true